### ISSUE TITLE
Testing new data file leads to error message

### ISSUE THREAD

**Issue by atillmanns** [bcgov/shinywqg#88]
I'm trying to test out a new .csv file with guideline values.  I have made the changes to the mod_data.R file as described in the read_me but when I try to deploy the app locally, I get this error message:

> pkgload::load_all(".")
ℹ Loading shinywqg
> webshot::install_phantomjs()
Error in if (!force && is_phantomjs_version_latest(version)) { : 
  missing value where TRUE/FALSE needed

**Comment by aylapear** [comment]
I was able to launch the app locally without errors. Try to update the `webshot` package and see if that helps. If that doesn't help then try comment or skip over the webshot line and try to run the next line `shinywqg::run_wqg_app()` to see if the app will launch.

**Comment by atillmanns** [comment]
I was able to launch the app locally by skipping the webshot line.
